calibrate:
  r_beam_px: 35
  ring_analysis:
    gauss_sigma: 5.0
    div_gmm_components: 5
    div_gmm_prob_main_lt: 0.01
    div_gmm_max_samples: 100000
    div_gmm_seed: 0
    dbscan_eps: 5.0
    dbscan_min_samples: 10
    circle_r2_min: 0.5
    global_refine_bounds_half_width_px: 50.0
    final_max_radius_px: 500.0
    final_skip_first_ring: true
    final_keep_first_ring_if_rout_gap_le_px: 50.0
    final_ring_radial_dr: 0.5
    final_ring_target_width_px: 2.0
    final_keep_smallest_k: 3
    final_interval_overlap_tol_px: 0.0
  detector_geometry:
    pixel_size:
    - 0.000172
    - 0.000172
    rot1: 0.0
    rot2: 0.0
    rot3: 0.0
  wavelength: 1.445
  mask_mode: f
  calibrant: AgBh

subtract:
  method: point_match
  sample_form: Porod-plus-linear
  buffer_form: linear
  point_match_factor: 0.995

fit_mixture:
  maxit: 100
  max_nph: 3
  plot_I_q: false
  plot_logI_logq: false
  plot_logI_q: true
